name: Test nextflow pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NXF_VER: "24.10.6"
  NXF_WORK: ${{ github.workspace }}/work

defaults:
      run:
        shell: bash -el {0}

jobs:
  test:
    strategy:
      matrix:
        tree_format: ["newick", "nexus"]
        profile: ["mamba", "conda"]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/install-dependencies
      - name: Run test ${{ matrix.tree_format }} ${{ matrix.profile }}
        run: |
          nextflow run main.nf -profile test,${{ matrix.profile }} -params-file assets/test/input/params_${{ matrix.tree_format }}.json
          make md5sum
